name: L1EM
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bedtools
  - bwa
  - numpy=1.25.2
  - pysam=0.23.3
  - python=3.11
  - samtools
  - scipy=1.10.1
  - sra-tools
  - trim-galore
  - pigz
  - flux-simulator
  - ipykernel
  - openjdk=21
  - wget
  - ipython=8.14
  - scikit-learn
  - pip:
      - appdirs==1.4.4
      - argparse-dataclass==2.0.0
      - attrs==22.2.0
      - beers-utils==0.2.0
      - beers2==2.0
      - boto3==1.26.85
      - botocore==1.29.85
      - camparee==0.4.2
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.2.1
      - cloudpathlib==0.13.0
      - conda-env-export==0.6.1
      - conda-inject==1.3.2
      - configargparse==1.5.3
      - connection-pool==0.0.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.33
      - cytoolz==1.0.1
      - datrie==0.8.2
      - docutils==0.19
      - dpath==2.1.4
      - fastjsonschema==2.16.3
      - filelock==3.18.0
      - fonttools==4.39.0
      - fsspec==2025.5.1
      - gitdb==4.0.10
      - gitpython==3.1.31
      - humanfriendly==10.0
      - idna==3.4
      - immutables==0.21
      - jax==0.4.38
      - jaxlib==0.4.38
      - jinja2==3.1.2
      - jmespath==1.0.1
      - jsonschema==4.17.3
      - jupyter-core==5.2.0
      - kiwisolver==1.4.4
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - multipledispatch==1.0.0
      - nbformat==5.7.3
      - networkx==3.5
      - numpy==1.24.2
      - numpyro==0.18.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - opt-einsum==3.4.0
      - packaging==23.0
      - pandas==1.5.3
      - pillow==9.4.0
      - plac==1.3.5
      - platformdirs==3.1.0
      - prettytable==3.6.0
      - psutil==5.9.4
      - pulp==2.7.0
      - pydantic==1.10.5
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - pysam==0.20.0
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pyyaml==6.0
      - referencing==0.36.2
      - requests==2.28.2
      - reretry==0.11.8
      - roman==4.0
      - rpds-py==0.26.0
      - ruamel-yaml==0.17.40
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.6.0
      - six==1.16.0
      - smart-open==6.3.0
      - smmap==5.0.0
      - snakemake==7.24.0
      - snakemake-interface-common==1.20.1
      - snakemake-interface-executor-plugins==9.3.7
      - snakemake-interface-logger-plugins==1.2.3
      - snakemake-interface-report-plugins==1.1.0
      - snakemake-interface-storage-plugins==4.2.1
      - stopit==1.1.2
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==2.2.0
      - throttler==1.2.2
      - toolz==1.0.0
      - toposort==1.10
      - torch==2.1.2
      - tqdm==4.67.1
      - traitlets==5.9.0
      - triton==2.1.0
      - typing-extensions==4.5.0
      - tzdata==2025.2
      - urllib3==1.26.14
      - wcwidth==0.2.6
      - wrapt==1.15.0
      - yte==1.5.1
